#include "xiangqi/engine.hpp"

#include <charconv>
#include <cstddef>
#include <filesystem>
#include <sstream>
#include <system_error>

#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#else
#include <cerrno>
#include <csignal>
#include <pthread.h>
#include <sys/types.h>
#include <sys/wait.h>
#include <unistd.h>
#endif

namespace xiangqi {
namespace {

constexpr std::size_t kMaxCommandHistory = 1024;

std::vector<std::string> split_words(std::string_view line) {
    std::istringstream stream{std::string(line)};
    std::vector<std::string> words;
    std::string word;
    while (stream >> word) words.push_back(std::move(word));
    return words;
}

template <typename Integer>
bool parse_integer(std::string_view text, Integer& value) {
    if (text.empty()) return false;
    const auto result = std::from_chars(text.data(), text.data() + text.size(), value);
    return result.ec == std::errc{} && result.ptr == text.data() + text.size();
}

#ifndef _WIN32
bool write_pipe(int descriptor, std::string_view data) {
    sigset_t pipe_signal{};
    if (sigemptyset(&pipe_signal) != 0 || sigaddset(&pipe_signal, SIGPIPE) != 0) return false;

    sigset_t old_mask{};
    if (pthread_sigmask(SIG_BLOCK, &pipe_signal, &old_mask) != 0) return false;

    const char* current = data.data();
    std::size_t remaining = data.size();
    int write_error = 0;
    while (remaining > 0) {
        const ssize_t written = ::write(descriptor, current, remaining);
        if (written > 0) {
            current += written;
            remaining -= static_cast<std::size_t>(written);
        } else if (written < 0 && errno == EINTR) {
            continue;
        } else {
            write_error = written < 0 ? errno : EIO;
            break;
        }
    }

    // A blocked SIGPIPE remains pending after write(2) reports EPIPE. Consume
    // the signal generated by this write before restoring the old mask.
    if (write_error == EPIPE) {
        const timespec timeout{0, 0};
        while (sigtimedwait(&pipe_signal, nullptr, &timeout) < 0 && errno == EINTR) {}
    }
    const bool restored = pthread_sigmask(SIG_SETMASK, &old_mask, nullptr) == 0;
    return write_error == 0 && restored;
}
#endif

} // namespace

EngineProtocol::EngineProtocol(std::string protocol) : protocol_(std::move(protocol)) {}

std::string EngineProtocol::option_command(std::string_view name, std::string_view value) const {
    if (protocol_ == "ucci") return "setoption " + std::string(name) + " " + std::string(value);
    return "setoption name " + std::string(name) + " value " + std::string(value);
}

bool EngineProtocol::validate_move(std::string_view move) {
    return move.size() == 4 && move[0] >= 'a' && move[0] <= 'i' && move[2] >= 'a' && move[2] <= 'i' &&
           move[1] >= '0' && move[1] <= '9' && move[3] >= '0' && move[3] <= '9';
}

std::optional<std::pair<std::string, std::optional<std::string>>>
EngineProtocol::parse_bestmove(std::string_view line) {
    const auto words = split_words(line);
    if (words.size() < 2 || words[0] != "bestmove" || !validate_move(words[1])) return std::nullopt;
    std::optional<std::string> ponder;
    for (std::size_t i = 2; i + 1 < words.size(); ++i) {
        if (words[i] == "ponder" && validate_move(words[i + 1])) {
            ponder = words[i + 1];
            break;
        }
    }
    return std::pair{words[1], ponder};
}

ThinkData EngineProtocol::parse_info(std::string_view line) {
    ThinkData data;
    const auto words = split_words(line);
    for (std::size_t i = 0; i < words.size(); ++i) {
        const auto set_int = [&](std::optional<int>& field) {
            if (i + 1 < words.size()) {
                int value = 0;
                if (parse_integer(words[i + 1], value)) {
                    field = value;
                    ++i;
                }
            }
        };
        const auto set_long = [&](std::optional<std::int64_t>& field) {
            if (i + 1 < words.size()) {
                std::int64_t value = 0;
                if (parse_integer(words[i + 1], value)) {
                    field = value;
                    ++i;
                }
            }
        };
        if (words[i] == "depth") set_int(data.depth);
        else if (words[i] == "nps") set_long(data.nps);
        else if (words[i] == "time") set_long(data.time);
        else if (words[i] == "multipv") set_int(data.pv);
        else if (words[i] == "score" && i + 2 < words.size()) {
            if (words[i + 1] == "cp") {
                ++i;
                set_int(data.score);
            } else if (words[i + 1] == "mate") {
                ++i;
                set_int(data.mate);
            }
        } else if (words[i] == "mate") {
            set_int(data.mate);
        } else if (words[i] == "pv") {
            for (++i; i < words.size(); ++i) {
                if (validate_move(words[i])) data.detail.push_back(words[i]);
            }
            break;
        }
    }
    return data;
}

Engine::Engine(EngineConfig config, EngineCallbacks callbacks)
    : config_(std::move(config)), callbacks_(std::move(callbacks)), protocol_(config_.protocol) {}

Engine::~Engine() {
    close();
}

bool Engine::start() {
    // 检查、清理残留子进程、spawn、启动握手在同一次生命周期操作内完成，
    // 否则并发 start() 会双重 spawn 并覆盖句柄（旧子进程泄漏，reader 线程被重复赋值）。
    std::lock_guard lifecycle_lock(lifecycle_mutex_);
    if (running_) return true;
    close_locked();
    if (config_.path.empty()) {
        if (callbacks_.error) callbacks_.error("引擎路径为空");
        return false;
    }
    // 引擎可能相对自身目录加载资源（Java 版 Runtime.exec 同样传入父目录）。
    std::string child_cwd;
    std::error_code fs_error;
    const auto parent_dir = std::filesystem::path(config_.path).parent_path();
    if (!parent_dir.empty() && std::filesystem::exists(parent_dir, fs_error)) {
        child_cwd = parent_dir.string();
    }

#ifdef _WIN32
    SECURITY_ATTRIBUTES security{sizeof(SECURITY_ATTRIBUTES), nullptr, TRUE};
    HANDLE child_stdin_read = nullptr;
    HANDLE child_stdin_write = nullptr;
    HANDLE child_stdout_read = nullptr;
    HANDLE child_stdout_write = nullptr;
    if (!CreatePipe(&child_stdin_read, &child_stdin_write, &security, 0)) {
        if (callbacks_.error) callbacks_.error("创建引擎管道失败");
        return false;
    }
    if (!CreatePipe(&child_stdout_read, &child_stdout_write, &security, 0)) {
        CloseHandle(child_stdin_read);
        CloseHandle(child_stdin_write);
        if (callbacks_.error) callbacks_.error("创建引擎管道失败");
        return false;
    }
    SetHandleInformation(child_stdin_write, HANDLE_FLAG_INHERIT, 0);
    SetHandleInformation(child_stdout_read, HANDLE_FLAG_INHERIT, 0);
    STARTUPINFOA startup{};
    startup.cb = sizeof(startup);
    startup.dwFlags = STARTF_USESTDHANDLES;
    startup.hStdInput = child_stdin_read;
    startup.hStdOutput = child_stdout_write;
    startup.hStdError = child_stdout_write;
    PROCESS_INFORMATION process{};
    const BOOL created =
        CreateProcessA(config_.path.c_str(), nullptr, nullptr, nullptr, TRUE, CREATE_NO_WINDOW, nullptr,
                       child_cwd.empty() ? nullptr : child_cwd.c_str(), &startup, &process);
    CloseHandle(child_stdin_read);
    CloseHandle(child_stdout_write);
    if (!created) {
        CloseHandle(child_stdin_write);
        CloseHandle(child_stdout_read);
        if (callbacks_.error) callbacks_.error("启动引擎进程失败");
        return false;
    }
    CloseHandle(process.hThread);
    {
        std::lock_guard lock(process_mutex_);
        process_handle_ = process.hProcess;
        input_write_ = child_stdin_write;
        output_read_ = child_stdout_read;
    }
#else
    int stdin_pipe[2]{};
    int stdout_pipe[2]{};
    if (pipe(stdin_pipe) != 0) {
        if (callbacks_.error) callbacks_.error("创建引擎管道失败");
        return false;
    }
    if (pipe(stdout_pipe) != 0) {
        ::close(stdin_pipe[0]); ::close(stdin_pipe[1]);
        if (callbacks_.error) callbacks_.error("创建引擎管道失败");
        return false;
    }
    const pid_t process_id = fork();
    if (process_id == 0) {
        if (!child_cwd.empty()) chdir(child_cwd.c_str());
        dup2(stdin_pipe[0], STDIN_FILENO);
        dup2(stdout_pipe[1], STDOUT_FILENO);
        dup2(stdout_pipe[1], STDERR_FILENO);
        ::close(stdin_pipe[0]); ::close(stdin_pipe[1]); ::close(stdout_pipe[0]); ::close(stdout_pipe[1]);
        execlp(config_.path.c_str(), config_.path.c_str(), static_cast<char*>(nullptr));
        _exit(127);
    }
    if (process_id < 0) {
        ::close(stdin_pipe[0]); ::close(stdin_pipe[1]); ::close(stdout_pipe[0]); ::close(stdout_pipe[1]);
        if (callbacks_.error) callbacks_.error("启动引擎进程失败");
        return false;
    }
    ::close(stdin_pipe[0]);
    ::close(stdout_pipe[1]);
    {
        std::lock_guard lock(process_mutex_);
        process_id_ = process_id;
        input_write_ = stdin_pipe[1];
        output_read_ = stdout_pipe[0];
    }
#endif

    running_ = true;
    reader_thread_ = std::thread(&Engine::reader_loop, this);
    // 子进程若在握手前退出，reader 会清掉 running_（或写入直接 EPIPE），两种情况都视为启动失败。
    bool started = send(config_.protocol == "ucci" ? "ucci" : "uci");
    if (started) {
        for (const auto& [name, value] : config_.options) {
            if (!send(protocol_.option_command(name, value))) {
                started = false;
                break;
            }
        }
    }
    if (!started || !running_) {
        close_locked();
        if (callbacks_.error) callbacks_.error("引擎启动失败");
        return false;
    }
    return true;
}

bool Engine::running() const noexcept {
    return running_;
}

bool Engine::send(std::string command) {
    {
        std::lock_guard lock(command_mutex_);
        if (commands_.size() >= kMaxCommandHistory) commands_.pop_front();
        commands_.push_back(command);
    }
    command.push_back('\n');
    // 只在取句柄时持锁；阻塞 I/O 期间不持有 process_mutex_，
    // 否则引擎停止消费 stdin 时 close() 拿不到锁，无法终止进程（管道写满即死锁）。
#ifdef _WIN32
    void* input_write = nullptr;
    {
        std::lock_guard process_lock(process_mutex_);
        input_write = input_write_;
    }
    if (input_write != nullptr && running_) {
        DWORD written = 0;
        if (!WriteFile(static_cast<HANDLE>(input_write), command.data(),
                       static_cast<DWORD>(command.size()), &written, nullptr)) {
            running_ = false;
            return false;
        }
    } else if (input_write != nullptr) {
        return false;
    }
#else
    int input_write = -1;
    {
        std::lock_guard process_lock(process_mutex_);
        input_write = input_write_;
    }
    if (input_write >= 0 && running_) {
        if (!write_pipe(input_write, command)) {
            running_ = false;
            return false;
        }
    } else if (input_write >= 0) {
        return false;
    }
#endif
    return true;
}

void Engine::reader_loop() {
    std::string line;
    char character = 0;
#ifdef _WIN32
    void* output_read = nullptr;
    {
        std::lock_guard lock(process_mutex_);
        output_read = output_read_;
    }
#else
    int output_read = -1;
    {
        std::lock_guard lock(process_mutex_);
        output_read = output_read_;
    }
#endif
    while (running_) {
#ifdef _WIN32
        DWORD read = 0;
        if (output_read == nullptr || !ReadFile(static_cast<HANDLE>(output_read), &character, 1, &read, nullptr) || read == 0) break;
#else
        const ssize_t read = ::read(output_read, &character, 1);
        if (read < 0 && errno == EINTR) continue;
        if (read <= 0) break;
#endif
        if (character == '\n') {
            consume_line(line);
            line.clear();
        } else if (character != '\r') {
            line += character;
        }
    }
    if (!line.empty()) consume_line(line);
    running_ = false;
#ifdef _WIN32
    void* input_write = nullptr;
    {
        std::lock_guard lock(process_mutex_);
        input_write = input_write_;
        input_write_ = nullptr;
    }
    if (input_write != nullptr) CloseHandle(static_cast<HANDLE>(input_write));
#else
    int input_write = -1;
    {
        std::lock_guard lock(process_mutex_);
        input_write = input_write_;
        input_write_ = -1;
    }
    if (input_write >= 0) ::close(input_write);
#endif
}

void Engine::consume_line(std::string_view line) {
    if (line.find("bestmove") != std::string_view::npos) handle_bestmove(line);
    else if (line.find("depth") != std::string_view::npos || line.find("nps") != std::string_view::npos) handle_info(line);
}

void Engine::handle_bestmove(std::string_view line) {
    if (stop_flag_) {
        stop_flag_ = false;
        return;
    }
    if (pondering_ && !ponderhit_sent_) {
        pondering_ = false;
        ponderhit_sent_ = false;
        return;
    }
    pondering_ = false;
    const auto parsed = EngineProtocol::parse_bestmove(line);
    if (!parsed) return;
    if (callbacks_.best_move) {
        std::optional<std::string> ponder;
        if (parsed->second) ponder = *parsed->second;
        callbacks_.best_move(parsed->first, ponder);
    }
}

void Engine::handle_info(std::string_view line) {
    auto data = EngineProtocol::parse_info(line);
    if (data.depth && *data.depth < 5) stop_flag_ = false;
    if (!data.detail.empty() && callbacks_.think_detail) callbacks_.think_detail(data);
}

void Engine::analysis(std::string_view fen, const std::vector<std::string>& moves,
                      std::vector<std::string> tactic_list) {
    stop();
    if (thread_num_changed_) {
        send(protocol_.option_command("Threads", std::to_string(thread_num_)));
        thread_num_changed_ = false;
    }
    if (hash_size_changed_) {
        send(protocol_.option_command("Hash", std::to_string(hash_size_)));
        hash_size_changed_ = false;
    }
    std::string position = "position fen " + std::string(fen);
    if (!moves.empty()) {
        position += " moves";
        for (const auto& move : moves) position += ' ' + move;
    }
    send(position);
    std::string go;
    switch (analysis_model_) {
        case AnalysisModel::FixedSteps: go = "go depth " + std::to_string(analysis_value_); break;
        case AnalysisModel::FixedTime: go = "go movetime " + std::to_string(analysis_value_); break;
        case AnalysisModel::FixedNodes: go = "go nodes " + std::to_string(analysis_value_); break;
        case AnalysisModel::Infinite: go = "go infinite"; break;
    }
    if (!tactic_list.empty()) {
        go += " searchmoves";
        for (const auto& move : tactic_list) go += ' ' + move;
    }
    send(go);
}

void Engine::move_now() {
    send("stop");
}

void Engine::stop() {
    stop_flag_ = true;
    pondering_ = false;
    ponderhit_sent_ = false;
    send("stop");
}

void Engine::start_ponder(std::string_view fen, const std::vector<std::string>& moves,
                          std::string_view ponder_move) {
    stop();
    std::string position = "position fen " + std::string(fen);
    if (!moves.empty() || !ponder_move.empty()) {
        position += " moves";
        for (const auto& move : moves) position += ' ' + move;
        if (!ponder_move.empty()) position += ' ' + std::string(ponder_move);
    }
    send(position);
    send("go ponder" + ponder_limit());
    stop_flag_ = false;
    pondering_ = true;
    ponderhit_sent_ = false;
}

void Engine::ponderhit() {
    if (pondering_ && !ponderhit_sent_) {
        send("ponderhit");
        ponderhit_sent_ = true;
    }
}

std::string Engine::ponder_limit() const {
    switch (analysis_model_) {
        case AnalysisModel::FixedSteps: return " depth " + std::to_string(analysis_value_);
        case AnalysisModel::FixedTime: return " movetime " + std::to_string(analysis_value_);
        case AnalysisModel::FixedNodes: return " nodes " + std::to_string(analysis_value_);
        case AnalysisModel::Infinite: return {};
    }
    return {};
}

void Engine::set_thread_num(int value) {
    if (thread_num_ != value) { thread_num_ = value; thread_num_changed_ = true; }
}

void Engine::set_hash_size(int value) {
    if (hash_size_ != value) { hash_size_ = value; hash_size_changed_ = true; }
}

void Engine::set_analysis_model(AnalysisModel model, std::int64_t value) {
    analysis_model_ = model;
    analysis_value_ = value;
}

std::vector<std::string> Engine::sent_commands() const {
    std::lock_guard lock(command_mutex_);
    return {commands_.begin(), commands_.end()};
}

void Engine::close() {
    std::lock_guard lifecycle_lock(lifecycle_mutex_);
    close_locked();
}

// 假定调用方已持有 lifecycle_mutex_（start() 在同一生命周期段内复用）。
void Engine::close_locked() {
    const bool had_process =
        [&] {
            std::lock_guard lock(process_mutex_);
#ifdef _WIN32
            return input_write_ != nullptr || output_read_ != nullptr || process_handle_ != nullptr;
#else
            return input_write_ >= 0 || output_read_ >= 0 || process_id_ >= 0;
#endif
        }();
    if (had_process) {
        if (running_) send("quit");
        running_ = false;
#ifdef _WIN32
        void* input_write = nullptr;
        void* process_handle = nullptr;
        {
            std::lock_guard lock(process_mutex_);
            input_write = input_write_;
            input_write_ = nullptr;
            process_handle = process_handle_;
            process_handle_ = nullptr;
        }
        if (input_write != nullptr) CloseHandle(static_cast<HANDLE>(input_write));
        if (process_handle != nullptr) {
            WaitForSingleObject(static_cast<HANDLE>(process_handle), 1000);
            if (WaitForSingleObject(static_cast<HANDLE>(process_handle), 0) == WAIT_TIMEOUT) {
                TerminateProcess(static_cast<HANDLE>(process_handle), 1);
            }
            CloseHandle(static_cast<HANDLE>(process_handle));
        }
#else
        int input_write = -1;
        int process_id = -1;
        {
            std::lock_guard lock(process_mutex_);
            input_write = input_write_;
            input_write_ = -1;
            process_id = process_id_;
            process_id_ = -1;
        }
        if (input_write >= 0) ::close(input_write);
        if (process_id >= 0) {
            int status = 0;
            pid_t waited = 0;
            do {
                waited = waitpid(process_id, &status, WNOHANG);
            } while (waited < 0 && errno == EINTR);
            if (waited == 0) {
                if (kill(process_id, SIGTERM) < 0 && errno != ESRCH) {
                    // waitpid below still handles a child that exits between
                    // the status check and kill(2).
                }
                do {
                    waited = waitpid(process_id, &status, 0);
                } while (waited < 0 && errno == EINTR);
            }
        }
#endif
    } else {
        running_ = false;
    }
    if (reader_thread_.joinable()) reader_thread_.join();
#ifdef _WIN32
    void* output_read = nullptr;
    {
        std::lock_guard lock(process_mutex_);
        output_read = output_read_;
        output_read_ = nullptr;
    }
    if (output_read != nullptr) CloseHandle(static_cast<HANDLE>(output_read));
#else
    int output_read = -1;
    {
        std::lock_guard lock(process_mutex_);
        output_read = output_read_;
        output_read_ = -1;
    }
    if (output_read >= 0) ::close(output_read);
#endif
}

} // namespace xiangqi
